package amisgo

import (
	"github.com/zrcoder/amisgo/comp"
	icomp "github.com/zrcoder/amisgo/internal/comp"

	"github.com/zrcoder/amisgo/model"
)

func (e *App) Action() comp.Action                           { return icomp.NewAction(e.mux) }
func (e *App) Alert() comp.Alert                             { return icomp.NewAlert() }
func (e *App) AnchorNav() comp.AnchorNav                     { return icomp.NewAnchorNav() }
func (e *App) App() comp.App                                 { return icomp.NewApp() }
func (e *App) Audio() comp.Audio                             { return icomp.NewAudio() }
func (e *App) Avatar() comp.Avatar                           { return icomp.NewAvatar() }
func (e *App) Barcode() comp.Barcode                         { return icomp.NewBarcode() }
func (e *App) Breadcrumb() comp.Breadcrumb                   { return icomp.NewBreadcrumb() }
func (e *App) Button() comp.Action                           { return icomp.NewButton(e.mux) }
func (e *App) ButtonGroup() comp.ButtonGroup                 { return icomp.NewButtonGroup() }
func (e *App) ButtonGroupSelect() comp.Select                { return icomp.NewButtonGroupSelect() }
func (e *App) ButtonToolbar() comp.ButtonToolbar             { return icomp.NewButtonToolbar() }
func (e *App) Calendar() comp.Calendar                       { return icomp.NewCalendar() }
func (e *App) Card() comp.Card                               { return icomp.NewCard() }
func (e *App) Cards() comp.Cards                             { return icomp.NewCards() }
func (e *App) Carousel() comp.Carousel                       { return icomp.NewCarousel() }
func (e *App) ChainedSelect() comp.ChainedSelect             { return icomp.NewChainedSelect() }
func (e *App) Chart() comp.Chart                             { return icomp.NewChart(e.mux) }
func (e *App) ChartRadios() comp.ChartRadios                 { return icomp.NewChartRadios() }
func (e *App) Checkbox() comp.Checkbox                       { return icomp.NewCheckbox() }
func (e *App) Checkboxes() comp.Checkboxes                   { return icomp.NewCheckboxes() }
func (e *App) Code() comp.Code                               { return icomp.NewCode() }
func (e *App) Collapse() comp.Collapse                       { return icomp.NewCollapse() }
func (e *App) CollapseGroup() comp.CollapseGroup             { return icomp.NewCollapseGroup() }
func (e *App) Color() comp.Color                             { return icomp.NewColor() }
func (e *App) Combo() comp.Combo                             { return icomp.NewCombo() }
func (e *App) ConditionBuilder() comp.ConditionBuilder       { return icomp.NewConditionBuilder() }
func (e *App) ConditionGroupValue() comp.ConditionGroupValue { return icomp.NewConditionGroupValue() }
func (e *App) Container() comp.Container                     { return icomp.NewContainer() }
func (e *App) Control() comp.Control                         { return icomp.NewControl() }
func (e *App) CopyButton() comp.CopyButton                   { return icomp.NewCopyButton() }
func (e *App) Crud() comp.Crud                               { return icomp.NewCrud(e.mux) }
func (e *App) CrudCards() comp.Crud                          { return icomp.NewCrudCards(e.mux) }
func (e *App) CrudList() comp.Crud                           { return icomp.NewCrudList(e.mux) }
func (e *App) CrudTable() comp.Crud                          { return icomp.NewCrudTable(e.mux) }
func (e *App) Custom() comp.Custom                           { return icomp.NewCustom() }
func (e *App) Date() comp.Date                               { return icomp.NewDate() }
func (e *App) DateRange() comp.DateRange                     { return icomp.NewDateRange() }
func (e *App) Dialog() comp.Dialog                           { return icomp.NewDialog() }
func (e *App) DialogAction() comp.DialogAction               { return icomp.NewDialogAction() }
func (e *App) DiffEditor() comp.DiffEditor                   { return icomp.NewDiffEditor() }
func (e *App) Divider() comp.Divider                         { return icomp.NewDivider() }
func (e *App) Drawer() comp.Drawer                           { return icomp.NewDrawer() }
func (e *App) DrawerAction() comp.DrawerAction               { return icomp.NewDrawerAction() }
func (e *App) DropdownButton() comp.DropdownButton           { return icomp.NewDropdownButton() }
func (e *App) Each() comp.Each                               { return icomp.NewEach() }
func (e *App) Editor() comp.Editor                           { return icomp.NewEditor() }
func (e *App) EmailAction() comp.EmailAction                 { return icomp.NewEmailAction() }
func (e *App) FieldSet() comp.FieldSet                       { return icomp.NewFieldSet() }
func (e *App) Flex() comp.Flex                               { return icomp.NewFlex() }
func (e *App) Form() comp.Form                               { return icomp.NewForm(e.mux) }
func (e *App) Formula() comp.Formula                         { return icomp.NewFormula() }
func (e *App) Grid() comp.Grid                               { return icomp.NewGrid() }
func (e *App) Grid2D() comp.Grid2d                           { return icomp.NewGrid2D() }
func (e *App) GridNav() comp.GridNav                         { return icomp.NewGridNav() }
func (e *App) Group() comp.Group                             { return icomp.NewGroup() }
func (e *App) HBox() comp.HBox                               { return icomp.NewHBox() }
func (e *App) Hidden() comp.Hidden                           { return icomp.NewHidden() }
func (e *App) Html() comp.Tpl                                { return icomp.NewHtml() }
func (e *App) Icon() comp.Icon                               { return icomp.NewIcon() }
func (e *App) IconPicker() comp.IconPicker                   { return icomp.NewIconPicker() }
func (e *App) Iframe() comp.Iframe                           { return icomp.NewIframe() }
func (e *App) Image() comp.Image                             { return icomp.NewImage() }
func (e *App) Images() comp.Images                           { return icomp.NewImages() }
func (e *App) InputArray() comp.InputArray                   { return icomp.NewInputArray() }
func (e *App) InputCity() comp.InputCity                     { return icomp.NewInputCity() }
func (e *App) InputColor() comp.InputColor                   { return icomp.NewInputColor() }
func (e *App) InputDate() comp.InputDate                     { return icomp.NewInputDate() }
func (e *App) InputDateRange() comp.InputDateRange           { return icomp.NewInputDateRange() }
func (e *App) InputDatetime() comp.InputDatetime             { return icomp.NewInputDatetime() }
func (e *App) InputDatetimeRange() comp.InputDatetimeRange   { return icomp.NewInputDatetimeRange() }
func (e *App) InputEmail() comp.InputText                    { return icomp.NewInputEmail() }
func (e *App) InputExcel() comp.InputExcel                   { return icomp.NewInputExcel() }
func (e *App) InputFile() comp.InputFile                     { return icomp.NewInputFile(e.mux) }
func (e *App) InputGroup() comp.InputGroup                   { return icomp.NewInputGroup() }
func (e *App) InputImage() comp.InputImage                   { return icomp.NewInputImage(e.mux) }
func (e *App) InputKV() comp.InputKV                         { return icomp.NewInputKV() }
func (e *App) InputKVS() comp.InputKVS                       { return icomp.NewInputKVS() }
func (e *App) InputMonth() comp.InputMonth                   { return icomp.NewInputMonth() }
func (e *App) InputMonthRange() comp.InputMonthRange         { return icomp.NewInputMonthRange() }
func (e *App) InputNumber() comp.InputNumber                 { return icomp.NewInputNumber() }
func (e *App) InputPassword() comp.InputText                 { return icomp.NewInputPassword() }
func (e *App) InputQuarter() comp.InputQuarter               { return icomp.NewInputQuarter() }
func (e *App) InputQuarterRange() comp.InputQuarterRange     { return icomp.NewInputQuarterRange() }
func (e *App) InputRange() comp.InputRange                   { return icomp.NewInputRange() }
func (e *App) InputRating() comp.InputRating                 { return icomp.NewInputRating() }
func (e *App) InputRepeat() comp.InputRepeat                 { return icomp.NewInputRepeat() }
func (e *App) InputRichText() comp.InputRichText             { return icomp.NewInputRichText() }
func (e *App) InputSignature() comp.InputSignature           { return icomp.NewInputSignature() }
func (e *App) InputSubForm() comp.InputSubForm               { return icomp.NewInputSubForm() }
func (e *App) InputTable() comp.InputTable                   { return icomp.NewInputTable() }
func (e *App) InputTag() comp.InputTag                       { return icomp.NewInputTag() }
func (e *App) InputText() comp.InputText                     { return icomp.NewInputText() }
func (e *App) InputTime() comp.InputTime                     { return icomp.NewInputTime() }
func (e *App) InputTimeRange() comp.InputTimeRange           { return icomp.NewInputTimeRange() }
func (e *App) InputTree() comp.InputTree                     { return icomp.NewInputTree() }
func (e *App) InputUrl() comp.InputText                      { return icomp.NewInputUrl() }
func (e *App) InputYear() comp.InputYear                     { return icomp.NewInputYear() }
func (e *App) InputYearRange() comp.InputYearRange           { return icomp.NewInputYearRange() }
func (e *App) Json() comp.Json                               { return icomp.NewJson() }
func (e *App) JsonEditor() comp.Editor                       { return icomp.NewJsonEditor() }
func (e *App) JsonSchemaEditor() comp.JsonSchemaEditor       { return icomp.NewJsonSchemaEditor() }
func (e *App) Link() comp.Link                               { return icomp.NewLink() }
func (e *App) LinkAction() comp.LinkAction                   { return icomp.NewLinkAction() }
func (e *App) List() comp.List                               { return icomp.NewList() }
func (e *App) ListSelect() comp.ListSelect                   { return icomp.NewListSelect() }
func (e *App) LocationPicker() comp.LocationPicker           { return icomp.NewLocationPicker() }
func (e *App) Log() comp.Log                                 { return icomp.NewLog() }
func (e *App) Mapping() comp.Mapping                         { return icomp.NewMapping() }
func (e *App) Markdown() comp.Markdown                       { return icomp.NewMarkdown() }
func (e *App) MatrixCheckboxes() comp.MatrixCheckboxes       { return icomp.NewMatrixCheckboxes() }
func (e *App) MultilineText() comp.MultilineText             { return icomp.NewMultilineText() }
func (e *App) Nav() comp.Nav                                 { return icomp.NewNav() }
func (e *App) NestedSelect() comp.NestedSelect               { return icomp.NewNestedSelect() }
func (e *App) NewTimeline() comp.Timeline                    { return icomp.NewTimeline() }
func (e *App) Operation() comp.Operation                     { return icomp.NewOperation() }
func (e *App) OtherAction() comp.OtherAction                 { return icomp.NewOtherAction() }
func (e *App) Page() comp.Page                               { return icomp.NewPage(e.mux) }
func (e *App) Pagination() comp.Pagination                   { return icomp.NewPagination() }
func (e *App) PaginationWrapper() comp.PaginationWrapper     { return icomp.NewPaginationWrapper() }
func (e *App) Panel() comp.Panel                             { return icomp.NewPanel() }
func (e *App) Password() comp.Password                       { return icomp.NewPassword() }
func (e *App) Picker() comp.Picker                           { return icomp.NewPicker() }
func (e *App) Plain() comp.Plain                             { return icomp.NewPlain() }
func (e *App) Portlet() comp.Portlet                         { return icomp.NewPortlet() }
func (e *App) Progress() comp.Progress                       { return icomp.NewProgress() }
func (e *App) Property() comp.Property                       { return icomp.NewProperty() }
func (e *App) QRCode() comp.QRCode                           { return icomp.NewQRCode() }
func (e *App) Radio() comp.Radio                             { return icomp.NewRadio() }
func (e *App) Radios() comp.Radios                           { return icomp.NewRadios() }
func (e *App) ReloadAction() comp.ReloadAction               { return icomp.NewReloadAction() }
func (e *App) Remark() comp.Remark                           { return icomp.NewRemark() }
func (e *App) SearchBox() comp.SearchBox                     { return icomp.NewSearchBox() }
func (e *App) Select() comp.Select                           { return icomp.NewSelect() }
func (e *App) Service() comp.Service                         { return icomp.NewService(e.mux) }
func (e *App) SparkLine() comp.SparkLine                     { return icomp.NewSparkLine() }
func (e *App) Spinner() comp.Spinner                         { return icomp.NewSpinner() }
func (e *App) Static() comp.Static                           { return icomp.NewStatic() }
func (e *App) Status() comp.Status                           { return icomp.NewStatus() }
func (e *App) Steps() comp.Steps                             { return icomp.NewSteps() }
func (e *App) SubmitAction() comp.Action                     { return icomp.NewSubmitAction(e.mux) }
func (e *App) SvgIcon() comp.SvgIcon                         { return icomp.NewSvgIcon() }
func (e *App) Switch() comp.Switch                           { return icomp.NewSwitch() }
func (e *App) SwitchContainer() comp.SwitchContainer         { return icomp.NewSwitchContainer() }
func (e *App) Table() comp.Table                             { return icomp.NewTable() }
func (e *App) Table2() comp.Table                            { return icomp.NewTable2() }
func (e *App) TableView() comp.TableView                     { return icomp.NewTableView() }
func (e *App) Tabs() comp.Tabs                               { return icomp.NewTabs() }
func (e *App) TabsTransfer() comp.TabsTransfer               { return icomp.NewTabsTransfer() }
func (e *App) TabsTransferPicker() comp.TabsTransferPicker   { return icomp.NewTabsTransferPicker() }
func (e *App) Tag() comp.Tag                                 { return icomp.NewTag() }
func (e *App) Tasks() comp.Tasks                             { return icomp.NewTasks() }
func (e *App) Text() comp.Text                               { return icomp.NewText() }
func (e *App) Textarea() comp.Textarea                       { return icomp.NewTextarea() }
func (e *App) ToastAction() comp.ToastAction                 { return icomp.NewToastAction() }
func (e *App) TooltipWrapper() comp.TooltipWrapper           { return icomp.NewTooltipWrapper() }
func (e *App) Tpl() comp.Tpl                                 { return icomp.NewTpl() }
func (e *App) Transfer() comp.Transfer                       { return icomp.NewTransfer() }
func (e *App) TransferPicker() comp.TransferPicker           { return icomp.NewTransferPicker() }
func (e *App) TreeSelect() comp.TreeSelect                   { return icomp.NewTreeSelect() }
func (e *App) UUID() comp.UUID                               { return icomp.NewUUID() }
func (e *App) UrlAction() comp.UrlAction                     { return icomp.NewUrlAction() }
func (e *App) UsersSelect() comp.UserSelect                  { return icomp.NewUsersSelect() }
func (e *App) VBox() comp.VBox                               { return icomp.NewVBox() }
func (e *App) Video() comp.Video                             { return icomp.NewVideo() }
func (e *App) WangEditor() comp.WangEditor                   { return icomp.NewWangEditor() }
func (e *App) Watermark() comp.Watermark                     { return icomp.NewWatermark() }
func (e *App) WebComponent() comp.WebComponent               { return icomp.NewWebComponent() }
func (e *App) Wizard() comp.Wizard                           { return icomp.NewWizard() }
func (e *App) WizardStep() comp.WizardStep                   { return icomp.NewWizardStep() }
func (e *App) Words() comp.Words                             { return icomp.NewWords() }
func (e *App) Wrapper() comp.Wrapper                         { return icomp.NewWrapper() }
func (e *App) Number() comp.Number                           { return icomp.NewNumber() }
func (e *App) ThemeSelect() comp.Select                      { return icomp.NewSelect().Themes(e.mux, e.Conf.Templ) }
func (e *App) ThemeButtonGroupSelect() comp.Select {
	return icomp.NewButtonGroupSelect().Themes(e.mux, e.Conf.Templ)
}

func (e *App) AnchorNavSection() model.AnchorNavSection     { return model.NewAnchorNavSection() }
func (e *App) AutoFillHeight() model.AutoFillHeight         { return model.NewAutoFillHeight() }
func (e *App) AutoGenerateFilter() model.AutoGenerateFilter { return model.NewAutoGenerateFilter() }
func (e *App) Badge() model.Badge                           { return model.NewBadge() }
func (e *App) ComboCondition() model.ComboCondition         { return model.NewComboCondition() }
func (e *App) Component() model.Component                   { return model.NewComponent() }
func (e *App) Expandable() model.Expandable                 { return model.NewExpandable() }
func (e *App) FeedbackDialog() model.FeedbackDialog         { return model.NewFeedbackDialog() }
func (e *App) GridColumn() model.GridColumn                 { return model.NewGridColumn() }
func (e *App) HBoxColumn() model.HBoxColumn                 { return model.NewHBoxColumn() }
func (e *App) IconChecked() model.IconChecked               { return model.NewIconChecked() }
func (e *App) IconItem() model.IconItem                     { return model.NewIconItem() }
func (e *App) ImageToolbarAction() model.ImageToolbarAction { return model.NewImageToolbarAction() }
func (e *App) NavItem() model.NavItem                       { return model.NewNavItem() }
func (e *App) NavOverflow() model.NavOverflow               { return model.NewNavOverflow() }
func (e *App) NewTimelineItem() model.TimelineItem          { return model.NewTimelineItem() }
func (e *App) PortletTab() model.PortletTab                 { return model.NewPortletTab() }
func (e *App) QRCodeImageSettings() model.QRCodeImageSettings {
	return model.NewQRCodeImageSettings()
}
func (e *App) RowSelection() model.RowSelection { return model.NewRowSelection() }
func (e *App) RowSelectionOptions() model.RowSelectionOptions {
	return model.NewRowSelectionOptions()
}
func (e *App) SchemaApi() model.SchemaApi           { return model.NewSchemaApi() }
func (e *App) SchemaCopyable() model.SchemaCopyable { return model.NewSchemaCopyable() }
func (e *App) SchemaMessage() model.SchemaMessage   { return model.NewSchemaMessage() }
func (e *App) SchemaPopOver() model.SchemaPopOver   { return model.NewSchemaPopOver() }
func (e *App) State() model.State                   { return model.NewState() }
func (e *App) Step() model.Step                     { return model.NewStep() }
func (e *App) TableColumn() model.TableColumn       { return model.NewTableColumn() }
func (e *App) Toast() model.Toast                   { return model.NewToast() }
func (e *App) ChartConfig() model.ChartCfg          { return model.NewChartConfig() }
func (e *App) ChartSeries() model.ChartSeri         { return model.NewChartSeries() }
func (e *App) ChartAxis() model.ChartAxis           { return model.NewChartAxis() }
func (e *App) NewListItem() model.ListItem          { return model.NewListItem() }
func (e *App) Api() model.Api                       { return model.NewApi() }
func (e *App) BreadcrumbItem() model.BreadcrumbItem { return model.NewBreadcrumbItem() }
func (e *App) Column() model.Column                 { return model.NewColumn() }
func (e *App) EventAction() model.EventAction       { return model.NewEventAction() }
func (e *App) GridItem() model.GridItem             { return model.NewGridItem() }
func (e *App) Horizontal() model.Horizontal         { return model.NewHorizontal() }
func (e *App) ListBodyField() model.ListBodyField   { return model.NewListBodyField() }
func (e *App) NavLink() model.NavLink               { return model.NewNavLink() }
func (e *App) Option() model.Option                 { return model.NewOption() }
func (e *App) Options() model.Options               { return model.NewOptions() }
func (e *App) PageItem() model.PageItem             { return model.NewPageItem() }
func (e *App) PropertyItem() model.PropertyItem     { return model.NewPropertyItem() }
func (e *App) PullRefresh() model.PullRefresh       { return model.NewPullRefresh() }
func (e *App) Rule() model.Rule                     { return model.NewRule() }
func (e *App) Tab() model.Tab                       { return model.NewTab() }
