package amisgo

import (
	"github.com/zrcoder/amisgo/comp"
	"github.com/zrcoder/amisgo/model"
)

func (e *App) Action() comp.Action                           { return comp.NewAction(e.mux) }
func (e *App) Alert() comp.Alert                             { return comp.NewAlert() }
func (e *App) AnchorNav() comp.AnchorNav                     { return comp.NewAnchorNav() }
func (e *App) App() comp.App                                 { return comp.NewApp() }
func (e *App) Audio() comp.Audio                             { return comp.NewAudio() }
func (e *App) Avatar() comp.Avatar                           { return comp.NewAvatar() }
func (e *App) Barcode() comp.Barcode                         { return comp.NewBarcode() }
func (e *App) Breadcrumb() comp.Breadcrumb                   { return comp.NewBreadcrumb() }
func (e *App) Button() comp.Action                           { return comp.NewButton(e.mux) }
func (e *App) ButtonGroup() comp.ButtonGroup                 { return comp.NewButtonGroup() }
func (e *App) ButtonGroupSelect() comp.Select                { return comp.NewButtonGroupSelect() }
func (e *App) ButtonToolbar() comp.ButtonToolbar             { return comp.NewButtonToolbar() }
func (e *App) Calendar() comp.Calendar                       { return comp.NewCalendar() }
func (e *App) Card() comp.Card                               { return comp.NewCard() }
func (e *App) Cards() comp.Cards                             { return comp.NewCards() }
func (e *App) Carousel() comp.Carousel                       { return comp.NewCarousel() }
func (e *App) ChainedSelect() comp.ChainedSelect             { return comp.NewChainedSelect() }
func (e *App) Chart() comp.Chart                             { return comp.NewChart(e.mux) }
func (e *App) ChartRadios() comp.ChartRadios                 { return comp.NewChartRadios() }
func (e *App) Checkbox() comp.Checkbox                       { return comp.NewCheckbox() }
func (e *App) Checkboxes() comp.Checkboxes                   { return comp.NewCheckboxes() }
func (e *App) Code() comp.Code                               { return comp.NewCode() }
func (e *App) Collapse() comp.Collapse                       { return comp.NewCollapse() }
func (e *App) CollapseGroup() comp.CollapseGroup             { return comp.NewCollapseGroup() }
func (e *App) Color() comp.Color                             { return comp.NewColor() }
func (e *App) Combo() comp.Combo                             { return comp.NewCombo() }
func (e *App) ConditionBuilder() comp.ConditionBuilder       { return comp.NewConditionBuilder() }
func (e *App) ConditionGroupValue() comp.ConditionGroupValue { return comp.NewConditionGroupValue() }
func (e *App) Container() comp.Container                     { return comp.NewContainer() }
func (e *App) Control() comp.Control                         { return comp.NewControl() }
func (e *App) CopyButton() comp.CopyButton                   { return comp.NewCopyButton() }
func (e *App) Crud() comp.Crud                               { return comp.NewCrud(e.mux) }
func (e *App) CrudCards() comp.Crud                          { return comp.NewCrudCards(e.mux) }
func (e *App) CrudList() comp.Crud                           { return comp.NewCrudList(e.mux) }
func (e *App) CrudTable() comp.Crud                          { return comp.NewCrudTable(e.mux) }
func (e *App) Custom() comp.Custom                           { return comp.NewCustom() }
func (e *App) Date() comp.Date                               { return comp.NewDate() }
func (e *App) DateRange() comp.DateRange                     { return comp.NewDateRange() }
func (e *App) Dialog() comp.Dialog                           { return comp.NewDialog() }
func (e *App) DialogAction() comp.DialogAction               { return comp.NewDialogAction() }
func (e *App) DiffEditor() comp.DiffEditor                   { return comp.NewDiffEditor() }
func (e *App) Divider() comp.Divider                         { return comp.NewDivider() }
func (e *App) Drawer() comp.Drawer                           { return comp.NewDrawer() }
func (e *App) DrawerAction() comp.DrawerAction               { return comp.NewDrawerAction() }
func (e *App) DropdownButton() comp.DropdownButton           { return comp.NewDropdownButton() }
func (e *App) Each() comp.Each                               { return comp.NewEach() }
func (e *App) Editor() comp.Editor                           { return comp.NewEditor() }
func (e *App) EmailAction() comp.EmailAction                 { return comp.NewEmailAction() }
func (e *App) FieldSet() comp.FieldSet                       { return comp.NewFieldSet() }
func (e *App) Flex() comp.Flex                               { return comp.NewFlex() }
func (e *App) Form() comp.Form                               { return comp.NewForm(e.mux) }
func (e *App) Formula() comp.Formula                         { return comp.NewFormula() }
func (e *App) Grid() comp.Grid                               { return comp.NewGrid() }
func (e *App) Grid2D() comp.Grid2d                           { return comp.NewGrid2D() }
func (e *App) GridNav() comp.GridNav                         { return comp.NewGridNav() }
func (e *App) Group() comp.Group                             { return comp.NewGroup() }
func (e *App) HBox() comp.HBox                               { return comp.NewHBox() }
func (e *App) Hidden() comp.Hidden                           { return comp.NewHidden() }
func (e *App) Html() comp.Tpl                                { return comp.NewHtml() }
func (e *App) Icon() comp.Icon                               { return comp.NewIcon() }
func (e *App) IconPicker() comp.IconPicker                   { return comp.NewIconPicker() }
func (e *App) Iframe() comp.Iframe                           { return comp.NewIframe() }
func (e *App) Image() comp.Image                             { return comp.NewImage() }
func (e *App) Images() comp.Images                           { return comp.NewImages() }
func (e *App) InputArray() comp.InputArray                   { return comp.NewInputArray() }
func (e *App) InputCity() comp.InputCity                     { return comp.NewInputCity() }
func (e *App) InputColor() comp.InputColor                   { return comp.NewInputColor() }
func (e *App) InputDate() comp.InputDate                     { return comp.NewInputDate() }
func (e *App) InputDateRange() comp.InputDateRange           { return comp.NewInputDateRange() }
func (e *App) InputDatetime() comp.InputDatetime             { return comp.NewInputDatetime() }
func (e *App) InputDatetimeRange() comp.InputDatetimeRange   { return comp.NewInputDatetimeRange() }
func (e *App) InputEmail() comp.InputText                    { return comp.NewInputEmail() }
func (e *App) InputExcel() comp.InputExcel                   { return comp.NewInputExcel() }
func (e *App) InputFile() comp.InputFile                     { return comp.NewInputFile(e.mux) }
func (e *App) InputGroup() comp.InputGroup                   { return comp.NewInputGroup() }
func (e *App) InputImage() comp.InputImage                   { return comp.NewInputImage(e.mux) }
func (e *App) InputKV() comp.InputKV                         { return comp.NewInputKV() }
func (e *App) InputKVS() comp.InputKVS                       { return comp.NewInputKVS() }
func (e *App) InputMonth() comp.InputMonth                   { return comp.NewInputMonth() }
func (e *App) InputMonthRange() comp.InputMonthRange         { return comp.NewInputMonthRange() }
func (e *App) InputNumber() comp.InputNumber                 { return comp.NewInputNumber() }
func (e *App) InputPassword() comp.InputText                 { return comp.NewInputPassword() }
func (e *App) InputQuarter() comp.InputQuarter               { return comp.NewInputQuarter() }
func (e *App) InputQuarterRange() comp.InputQuarterRange     { return comp.NewInputQuarterRange() }
func (e *App) InputRange() comp.InputRange                   { return comp.NewInputRange() }
func (e *App) InputRating() comp.InputRating                 { return comp.NewInputRating() }
func (e *App) InputRepeat() comp.InputRepeat                 { return comp.NewInputRepeat() }
func (e *App) InputRichText() comp.InputRichText             { return comp.NewInputRichText() }
func (e *App) InputSignature() comp.InputSignature           { return comp.NewInputSignature() }
func (e *App) InputSubForm() comp.InputSubForm               { return comp.NewInputSubForm() }
func (e *App) InputTable() comp.InputTable                   { return comp.NewInputTable() }
func (e *App) InputTag() comp.InputTag                       { return comp.NewInputTag() }
func (e *App) InputText() comp.InputText                     { return comp.NewInputText() }
func (e *App) InputTime() comp.InputTime                     { return comp.NewInputTime() }
func (e *App) InputTimeRange() comp.InputTimeRange           { return comp.NewInputTimeRange() }
func (e *App) InputTree() comp.InputTree                     { return comp.NewInputTree() }
func (e *App) InputUrl() comp.InputText                      { return comp.NewInputUrl() }
func (e *App) InputYear() comp.InputYear                     { return comp.NewInputYear() }
func (e *App) InputYearRange() comp.InputYearRange           { return comp.NewInputYearRange() }
func (e *App) Json() comp.Json                               { return comp.NewJson() }
func (e *App) JsonEditor() comp.Editor                       { return comp.NewJsonEditor() }
func (e *App) JsonSchemaEditor() comp.JsonSchemaEditor       { return comp.NewJsonSchemaEditor() }
func (e *App) Link() comp.Link                               { return comp.NewLink() }
func (e *App) LinkAction() comp.LinkAction                   { return comp.NewLinkAction() }
func (e *App) List() comp.List                               { return comp.NewList() }
func (e *App) ListSelect() comp.ListSelect                   { return comp.NewListSelect() }
func (e *App) LocationPicker() comp.LocationPicker           { return comp.NewLocationPicker() }
func (e *App) Log() comp.Log                                 { return comp.NewLog() }
func (e *App) Mapping() comp.Mapping                         { return comp.NewMapping() }
func (e *App) Markdown() comp.Markdown                       { return comp.NewMarkdown() }
func (e *App) MatrixCheckboxes() comp.MatrixCheckboxes       { return comp.NewMatrixCheckboxes() }
func (e *App) MultilineText() comp.MultilineText             { return comp.NewMultilineText() }
func (e *App) Nav() comp.Nav                                 { return comp.NewNav() }
func (e *App) NestedSelect() comp.NestedSelect               { return comp.NewNestedSelect() }
func (e *App) NewTimeline() comp.Timeline                    { return comp.NewTimeline() }
func (e *App) Operation() comp.Operation                     { return comp.NewOperation() }
func (e *App) OtherAction() comp.OtherAction                 { return comp.NewOtherAction() }
func (e *App) Page() comp.Page                               { return comp.NewPage(e.mux) }
func (e *App) Pagination() comp.Pagination                   { return comp.NewPagination() }
func (e *App) PaginationWrapper() comp.PaginationWrapper     { return comp.NewPaginationWrapper() }
func (e *App) Panel() comp.Panel                             { return comp.NewPanel() }
func (e *App) Password() comp.Password                       { return comp.NewPassword() }
func (e *App) Picker() comp.Picker                           { return comp.NewPicker() }
func (e *App) Plain() comp.Plain                             { return comp.NewPlain() }
func (e *App) Portlet() comp.Portlet                         { return comp.NewPortlet() }
func (e *App) Progress() comp.Progress                       { return comp.NewProgress() }
func (e *App) Property() comp.Property                       { return comp.NewProperty() }
func (e *App) QRCode() comp.QRCode                           { return comp.NewQRCode() }
func (e *App) Radio() comp.Radio                             { return comp.NewRadio() }
func (e *App) Radios() comp.Radios                           { return comp.NewRadios() }
func (e *App) ReloadAction() comp.ReloadAction               { return comp.NewReloadAction() }
func (e *App) Remark() comp.Remark                           { return comp.NewRemark() }
func (e *App) SearchBox() comp.SearchBox                     { return comp.NewSearchBox() }
func (e *App) Select() comp.Select                           { return comp.NewSelect() }
func (e *App) Service() comp.Service                         { return comp.NewService(e.mux) }
func (e *App) SparkLine() comp.SparkLine                     { return comp.NewSparkLine() }
func (e *App) Spinner() comp.Spinner                         { return comp.NewSpinner() }
func (e *App) Static() comp.Static                           { return comp.NewStatic() }
func (e *App) Status() comp.Status                           { return comp.NewStatus() }
func (e *App) Steps() comp.Steps                             { return comp.NewSteps() }
func (e *App) SubmitAction() comp.Action                     { return comp.NewSubmitAction(e.mux) }
func (e *App) SvgIcon() comp.SvgIcon                         { return comp.NewSvgIcon() }
func (e *App) Switch() comp.SwitchControl                    { return comp.NewSwitch() }
func (e *App) SwitchContainer() comp.SwitchContainer         { return comp.NewSwitchContainer() }
func (e *App) Table() comp.Table                             { return comp.NewTable() }
func (e *App) Table2() comp.Table                            { return comp.NewTable2() }
func (e *App) TableView() comp.TableView                     { return comp.NewTableView() }
func (e *App) Tabs() comp.Tabs                               { return comp.NewTabs() }
func (e *App) TabsTransfer() comp.TabsTransfer               { return comp.NewTabsTransfer() }
func (e *App) TabsTransferPicker() comp.TabsTransferPicker   { return comp.NewTabsTransferPicker() }
func (e *App) Tag() comp.Tag                                 { return comp.NewTag() }
func (e *App) Tasks() comp.Tasks                             { return comp.NewTasks() }
func (e *App) Text() comp.Text                               { return comp.NewText() }
func (e *App) Textarea() comp.Textarea                       { return comp.NewTextarea() }
func (e *App) ToastAction() comp.ToastAction                 { return comp.NewToastAction() }
func (e *App) TooltipWrapper() comp.TooltipWrapper           { return comp.NewTooltipWrapper() }
func (e *App) Tpl() comp.Tpl                                 { return comp.NewTpl() }
func (e *App) Transfer() comp.Transfer                       { return comp.NewTransfer() }
func (e *App) TransferPicker() comp.TransferPicker           { return comp.NewTransferPicker() }
func (e *App) TreeSelect() comp.TreeSelect                   { return comp.NewTreeSelect() }
func (e *App) UUID() comp.UUID                               { return comp.NewUUID() }
func (e *App) UrlAction() comp.UrlAction                     { return comp.NewUrlAction() }
func (e *App) UsersSelect() comp.UserSelect                  { return comp.NewUsersSelect() }
func (e *App) VBox() comp.VBox                               { return comp.NewVBox() }
func (e *App) Video() comp.Video                             { return comp.NewVideo() }
func (e *App) WangEditor() comp.WangEditor                   { return comp.NewWangEditor() }
func (e *App) Watermark() comp.Watermark                     { return comp.NewWatermark() }
func (e *App) WebComponent() comp.WebComponent               { return comp.NewWebComponent() }
func (e *App) Wizard() comp.Wizard                           { return comp.NewWizard() }
func (e *App) WizardStep() comp.WizardStep                   { return comp.NewWizardStep() }
func (e *App) Words() comp.Words                             { return comp.NewWords() }
func (e *App) Wrapper() comp.Wrapper                         { return comp.NewWrapper() }

func (e *App) ThemeButtonGroupSelect() comp.Select {
	return comp.NewThemeButtonGroupSelect(e.mux, e.Conf.Templ)
}

func (e *App) ThemeSelect() comp.Select {
	return comp.NewThemeSelect(e.mux, e.Conf.Templ)
}

func (e *App) AnchorNavSection() model.AnchorNavSection     { return model.NewAnchorNavSection() }
func (e *App) AutoFillHeight() model.AutoFillHeight         { return model.NewAutoFillHeight() }
func (e *App) AutoGenerateFilter() model.AutoGenerateFilter { return model.NewAutoGenerateFilter() }
func (e *App) Badge() model.Badge                           { return model.NewBadge() }
func (e *App) ComboCondition() model.ComboCondition         { return model.NewComboCondition() }
func (e *App) Component() model.Component                   { return model.NewComponent() }
func (e *App) Expandable() model.Expandable                 { return model.NewExpandable() }
func (e *App) FeedbackDialog() model.FeedbackDialog         { return model.NewFeedbackDialog() }
func (e *App) GridColumn() model.GridColumn                 { return model.NewGridColumn() }
func (e *App) HBoxColumn() model.HBoxColumn                 { return model.NewHBoxColumn() }
func (e *App) IconChecked() model.IconChecked               { return model.NewIconChecked() }
func (e *App) IconItem() model.IconItem                     { return model.NewIconItem() }
func (e *App) ImageToolbarAction() model.ImageToolbarAction { return model.NewImageToolbarAction() }
func (e *App) NavItem() model.NavItem                       { return model.NewNavItem() }
func (e *App) NavOverflow() model.NavOverflow               { return model.NewNavOverflow() }
func (e *App) NewTimelineItem() model.TimelineItem          { return model.NewTimelineItem() }
func (e *App) PortletTab() model.PortletTab                 { return model.NewPortletTab() }
func (e *App) QRCodeImageSettings() model.QRCodeImageSettings {
	return model.NewQRCodeImageSettings()
}
func (e *App) RowSelection() model.RowSelection { return model.NewRowSelection() }
func (e *App) RowSelectionOptions() model.RowSelectionOptions {
	return model.NewRowSelectionOptions()
}
func (e *App) SchemaApi() model.SchemaApi           { return model.NewSchemaApi() }
func (e *App) SchemaCopyable() model.SchemaCopyable { return model.NewSchemaCopyable() }
func (e *App) SchemaMessage() model.SchemaMessage   { return model.NewSchemaMessage() }
func (e *App) SchemaPopOver() model.SchemaPopOver   { return model.NewSchemaPopOver() }
func (e *App) State() model.State                   { return model.NewState() }
func (e *App) Step() model.Step                     { return model.NewStep() }
func (e *App) TableColumn() model.TableColumn       { return model.NewTableColumn() }
func (e *App) Toast() model.Toast                   { return model.NewToast() }
func (e *App) ChartConfig() model.ChartCfg          { return model.NewChartConfig() }
func (e *App) ChartSeries() model.ChartSeri         { return model.NewChartSeries() }
func (e *App) ChartAxis() model.ChartAxis           { return model.NewChartAxis() }
func (e *App) NewListItem() model.ListItem          { return model.NewListItem() }
func (e *App) Api() model.Api                       { return model.NewApi() }
func (e *App) BreadcrumbItem() model.BreadcrumbItem { return model.NewBreadcrumbItem() }
func (e *App) Column() model.Column                 { return model.NewColumn() }
func (e *App) EventAction() model.EventAction       { return model.NewEventAction() }
func (e *App) GridItem() model.GridItem             { return model.NewGridItem() }
func (e *App) Horizontal() model.Horizontal         { return model.NewHorizontal() }
func (e *App) ListBodyField() model.ListBodyField   { return model.NewListBodyField() }
func (e *App) NavLink() model.NavLink               { return model.NewNavLink() }
func (e *App) Option() model.Option                 { return model.NewOption() }
func (e *App) Options() model.Options               { return model.NewOptions() }
func (e *App) PageItem() model.PageItem             { return model.NewPageItem() }
func (e *App) PropertyItem() model.PropertyItem     { return model.NewPropertyItem() }
func (e *App) PullRefresh() model.PullRefresh       { return model.NewPullRefresh() }
func (e *App) Rule() model.Rule                     { return model.NewRule() }
func (e *App) Tab() model.Tab                       { return model.NewTab() }
