// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"github.com/qiniu/x/errors"
	"github.com/zrcoder/amisgo"
)

const _ = true

type App struct {
	amisgo.Amis
}
//line examples/main_amis.gox:3
func (this *App) MainEntry() {
//line examples/main_amis.gox:3:1
	this.Page().Title("Example").Body(this.Page().Title("Inner"))
//line examples/main_amis.gox:7:1
	func() {
//line examples/main_amis.gox:7:1
		var _gop_err error
//line examples/main_amis.gox:7:1
		_gop_err = this.ListenAndServe(":9090")
//line examples/main_amis.gox:7:1
		if _gop_err != nil {
//line examples/main_amis.gox:7:1
			_gop_err = errors.NewFrame(_gop_err, "listenAndServe \":9090\"", "examples/main_amis.gox", 7, "main.MainEntry")
//line examples/main_amis.gox:7:1
			panic(_gop_err)
		}
//line examples/main_amis.gox:7:1
		return
	}()
}
func (this *App) Main() {
	amisgo.Gopt_App_Main(this)
}
func main() {
	new(App).Main()
}
