package form

import (
	"github.com/zrcoder/amisgo/comp"
)

var All = comp.Page().Title("").Data(comp.Data{"id": 1}).Body(
	comp.Form().AutoFocus(true).Body(
		comp.Html().Html("<p>html 片段, 可以用来添加说明性文字</p>"),
		comp.Divider(),
		comp.InputText().Name("var1").Label("文本"),
		comp.Divider(),
		comp.InputText().Name("withHelp").Label("带提示信息").Desc("这是一段描述文字"),
		comp.Divider(),
		comp.InputPassword().Name("password").Label("密码").Inline(true),
		comp.Divider(),
		comp.InputNumber().Name("number").Label("数字").Placeholder("").Inline(true).Value(5).Min(1).Max(10),
		comp.Divider(),
		comp.InputNumber().Name("number").Label("数字禁用").Placeholder("").Disabled(true).Inline(true).Value(5).Min(1).Max(10),
		comp.Divider(),
		comp.InputTag().Name("tag").Label("标签").Clearable(true).Options(
			comp.Option().Label("诸葛亮").Value("zhugeliang"),
			comp.Option().Label("曹操").Children(
				comp.Option().Label("曹丕").Value("caopi"),
				comp.Option().Label("曹植").Value("caozhi"),
			),
		),
		comp.Divider(),
		comp.InputText().Name("text-sug").Label("文本提示").Options(
			"lixiaolong",
			"zhouxingxing",
			"yipingpei",
			"liyuanfang",
		).AddOn(comp.Text().Label("$")),
		comp.Divider(),
		comp.InputText().Name("text-sug-multiple").Label("文本提示多选").Multiple(true).Options(
			"lixiaolong",
			"zhouxingxing",
			"yipingpei",
			"liyuanfang",
		),
		comp.Divider(),
		comp.Static().Name("static2").Label("静态展示").Value("这是静态展示的值").Copyable(comp.Schema{"content": "blabla"}),
		comp.Divider(),
		comp.Checkboxes().Name("checkboxes").Label("多选框").Value(3).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3).Disabled(true),
		),
		comp.Divider(),
		comp.Checkboxes().Name("checkboxesInline").Label("多选非联").Inline(false).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.Radios().Name("radios").Label("单选").Value(3).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.Radios().Name("radios").Label("单选禁用").Value(3).Disabled(true).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.Radios().Name("radios").Label("单选 非内联").Value(3).Inline(false).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.ButtonToolbar().Label("各种按钮").Buttons(
			comp.Action().Label("default"),
			comp.Action().Label("primary").Level("primary"),
			comp.Action().Label("secondary").Level("secondary"),
			comp.Action().Label("success").Level("success"),
			comp.Action().Label("warning").Level("warning"),
			comp.Action().Label("danger").Level("danger"),
			comp.Action().Label("light").Level("light"),
			comp.Action().Label("dark").Level("dark"),
			comp.Action().Label("link").Level("link"),
		),
		comp.Divider(),
		comp.ButtonGroupSelect().Name("btn-group").Label("按钮组").Description("类似于单选效果").Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.ButtonGroupSelect().Name("btn-group2").Label("按钮组").Description("可清除").Clearable(true).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.ButtonGroupSelect().Name("btn-group3").Label("按钮组").Description("可多选").Multiple(true).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.ListSelect().Name("list").Label("List").Desc("也差不多，只是展示方式不一样").Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.ListSelect().Name("list2").Label("List").Desc("可多选").Multiple(true).Options(
			comp.Option().Label("option 1").Value(1),
			comp.Option().Label("option 2").Value(2),
			comp.Option().Label("option 3").Value(3),
		),
		comp.Divider(),
		comp.ListSelect().Name("list4").Label("List").ImageClassName("thumb-lg").Desc("支持放张图片").Options(
			comp.Option().Label("option 1").Value(1).Image("/TODO"),
			comp.Option().Label("option 2").Value(2).Image("/TODO"),
			comp.Option().Label("option 3").Value(3).Image("/TODO"),
		),
		comp.Divider(),
		comp.ListSelect().Name("list5").Label("List").Desc("支持文字排版").Options(
			comp.Option().Label("option 1").Value(1).Body("<div class=\"m-l-sm m-r-sm m-b-sm m-t-xs\">\n                                <div class=\"text-md p-b-xs b-inherit b-b m-b-xs\">套餐：C01</div>\n                                <div class=\"text-sm\">CPU：22核</div>\n                                <div class=\"text-sm\">内存：10GB</div>\n                                <div class=\"text-sm\">SSD盘：1024GB</div>\n                            </div>"),
			comp.Option().Label("option 2").Value(2).Body("<div class=\"m-l-sm m-r-sm  m-b-sm m-t-xs\">\n                            <div class=\"text-md p-b-xs b-inherit b-b m-b-xs\">套餐：C02</div>\n                            <div class=\"text-sm\">CPU：23核</div>\n                            <div class=\"text-sm\">内存：11GB</div>\n                            <div class=\"text-sm\">SSD盘：1025GB</div>\n                            </div>"),
			comp.Option().Label("option 3").Value(3).Body("<div class=\"m-l-sm m-r-sm  m-b-sm m-t-xs\">\n                            <div class=\"text-md p-b-xs b-inherit b-b m-b-xs\">套餐：C03</div>\n                            <div class=\"text-sm\">CPU：24核</div>\n                            <div class=\"text-sm\">内存：12GB</div>\n                            <div class=\"text-sm\">SSD盘：1026GB</div>\n                            </div>"),
		),
		comp.Divider(),
		comp.InputRating().Count(5).Value(3).Label("评分").Name("rating").ReadOnly(false).Half(false),
		comp.Divider(),
		comp.Switch().Name("switch").Label("开关"),
		comp.Switch().Name("switch2").Label("开关开启").Value(true),
		comp.Switch().Name("switch3").Label("开关禁用").Value(true).Disabled(true),
		comp.Switch().Name("switch4").Label("开关文字").Value(true).OnText("开启").OffText("关闭"),
		comp.Switch().Name("switch5").Label("开关icon").Value(true).OnText(
			comp.Icon().Icon("fa fa-check-circle"),
		).OffText(
			comp.Icon().Icon("fa fa-times-circle"),
		),
		comp.Divider(),
		comp.Checkbox().Name("checkbox").Label("勾选框"),
		comp.Divider(),
		comp.Select().Name("select1").Label("下拉单选").Inline(true).Options(
			comp.Option().Label("选项1").Value(1),
			comp.Option().Label("选项2").Value(2),
			comp.Option().Label("内容很长很长的选项，内容很长很长的选项").Value(3),
		),
		comp.Divider(),
		comp.Select().Name("select2").Label("下拉单选禁用").Disabled(true).Inline(true).Options(
			comp.Option().Label("选项1").Value(1),
			comp.Option().Label("选项2").Value(2),
		),
		comp.Divider(),
		comp.Select().Name("select2").Label("多选").Multiple(true).Inline(true).Options(
			comp.Option().Label("选项1").Value(1),
			comp.Option().Label("选项2").Value(2),
		),
		comp.Divider(),
		comp.InputColor().Name("color").Inline(true).Label("Color"),
		comp.Divider(),
		comp.InputDate().Name("date").Inline(true).Label("日期"),
		comp.Divider(),
		comp.InputDatetime().Name("datetime").Inline(true).Label("日期+时间"),
		comp.Divider(),
		comp.InputTime().Name("time").Inline(true).Label("时间"),
		comp.Divider(),
		comp.InputMonth().Name("year-month").Inline(true).Label("年月").Value("-1month").InputFormat("YYYY-MM"),
		comp.Divider(),
		comp.InputDateRange().Name("date-range").Label("时间范围").Inline(true),
		comp.Divider(),
		comp.Group().Body(
			comp.InputDatetime().Name("starttime").Label("开始时间").MaxDate("${endtime}"),
			comp.InputDatetime().Name("endtime").Label("结束时间").MinDate("${starttime}"),
		),
		comp.Divider(),
		comp.Group().Label("时间范围").Gap("xs").Description("选择自定义后，可以选择日期范围").Body(
			comp.ButtonGroupSelect().Name("range1").Value("today").BtnActiveLevel("primary").Mode("inline").Options(
				comp.Option().Label("今天").Value("today"),
				comp.Option().Label("明天").Value("tommorow"),
				comp.Option().Label("近三天").Value("3days"),
				comp.Option().Label("近一周").Value("week"),
				comp.Option().Label("自定义").Value("custom"),
			),
			comp.InputDate().Name("starttime1").MaxDate("${endtime1}").VisibleOn("data.range1 == 'custom'").Mode("inlie"),
			comp.InputDate().Name("endtime1").MaxDate("${starttime1}").VisibleOn("data.range1 == 'custom'").Mode("inlie"),
		),
		comp.Divider(),
		comp.InputGroup().Size("sm").Inline(true).Label("Icon 组合").Body(
			comp.Icon().AddOnclassName("no-bg").ClassName("text-sm").Icon("search"),
			comp.InputText().Placeholder("搜索作业id/名称").InputClassName("b-l-none p-l-none").Name("jobName"),
		),
		comp.Divider(),
		comp.InputGroup().Label("各种组合").Inline(true).Body(
			comp.Select().Name("memUnits").Options(
				comp.Option().Label("Gi").Value("Gi"),
				comp.Option().Label("Mi").Value("Mi"),
				comp.Option().Label("Ki").Value("Ki"),
			).
				Value("Gi"),
			comp.Button().Label("Go"),
		),
		comp.Divider(),
		comp.InputExcel().Label("Excel解析").Name("excel"),
		comp.Divider(),
		comp.InputKVS().Name("kvs").Label("key-values").KeyItem(comp.Schema{"label": "字段名"}).ValueItems(
			comp.Switch().Name("primary").Label("是否是主键"),
			comp.Select().Name("type").Label("字段类型").Options("text", "int", "number"),
		),
		comp.Divider(),
		comp.InputImage().Name("image").Label("图片"),
		comp.Divider(),
		comp.InputImage().Name("image1").Label("图片带默认占位图").FrameImage("/TOTO.jpg").FixedSize(true).FixedSize("h-32"),
		comp.Divider(),
		comp.InputImage().Name("imageCrop").Label("图片带裁剪").Crop(comp.Schema{"aspectRation": 1.77777777}),
		comp.Divider(),
		comp.InputImage().Name("imageLimit").Label("图片带限制").Limit(comp.Schema{"width": 200, "height": 200}),
		comp.Divider(),
		comp.Textarea().Name("textarea").Label("多行文本"),
		comp.Divider(),
		comp.Textarea().Name("textarea").Label("多行文本禁用").Disabled(true),
		comp.Divider(),
		comp.Transfer().Name("a").Label("穿梭器").Source("/TODO").Searchable(true).SearchApi("/TODO").SelectMode("list").Sortable(true).Inline(true),
		comp.Divider(),
		comp.JsonEditor().Name("json").Value(`{"name":"Tom","age":27}`).Label("Json Editor"),
		comp.Divider(),
		comp.InputRichText().Name("html").Label("Rich Text").Value("<p>Just do <code>IT</code>!</p>"),
	),
)
